# Generated by Django 5.2.6 on 2026-01-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchiveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="档案标题")),
                ("year", models.IntegerField(verbose_name="年份")),
                (
                    "security_level",
                    models.CharField(
                        choices=[("公开", "公开"), ("内部", "内部"), ("绝密", "绝密")],
                        default="公开",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(verbose_name="档案详情")),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, verbose_name="是否加密"),
                ),
            ],
        ),
    ]
