# Generated by Django 5.2.6 on 2026-01-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus_archive", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=50)),
                ("serial_number", models.CharField(max_length=100)),
                ("access_level", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="ArchiveRecord",
        ),
    ]
